### ISSUE TITLE
"The data preprocessing phase of your submission is in progress"

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#331] opened 2016-12-06 15:32 UTC
The message received by email after submitting:
```
training=docker.synapse.org/syn7416180/dm-train-keras@sha256:a36b63d5904f3236b3c6bb2f979c333b9a8fe77f3bcfb2622271b35957c6a994
```
is
```
The data preprocessing phase of your submission (submission ID 7817937) to the Digital Mammography challenge is in progress.  Log files produced while your model is pre-processing the input data will be periodically uploaded here: https://www.synapse.org/#!Synapse:syn7817940.  Further notification will be provided when your model is complete.  Please direct any questions to the challenge forum, https://www.synapse.org/#!Synapse:syn4224222/discussion .
```
However, the submission does not include a pre-processing phase. Is that possible that the submission is treated as a pre-processing submission while it should actually be treated as a training submission?

**Comment by tschaffter** [comment] 2016-12-13 16:03
@brucehoff Can you comment on this issue?

**Comment by brucehoff** [comment] 2016-12-13 17:42
> Is that possible that the submission is treated as a pre-processing submission while it should actually be treated as a training submission?

No, the problem is only that the wrong message is being sent.  The fix is in the commit linked below.  (The commit includes another change, to add retry logic when updating the table tracking the data returned the the participant.)

https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/649f666405be59d8262a985d613fe7d7bdc79b2b

**Closed by brucehoff** 2016-12-13 17:42 UTC
