### ISSUE TITLE
Can not access model state file

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#207] opened 2016-11-10 08:06 UTC
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1196

**Comment by tschaffter** [comment] 2016-11-10 14:57
Duplicate of another question. We should not have displayed the link to download the trained model in the public training express lane before having the feature ready (we had three questions regarding this). Participant has been redirected to an answer.

**Closed by tschaffter** 2016-11-10 14:57 UTC
Labels: discussion forum

**Comment by brucehoff** [comment] 2016-11-10 22:44
Mea culpa.
