### ISSUE TITLE
Jobs should appear in the list immediately after submitting, not when they start running

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#208] opened 2016-11-10 08:06 UTC
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1197

**Comment by tschaffter** [comment] 2016-11-10 14:54
Duplicate of #190 . Answer to the participant when this feature is implemented.

**Comment by thomasyu888** [comment] 2016-11-22 23:49
Has this feature been implemented?

**Comment by tschaffter** [comment] 2016-11-23 16:29
Let's keep track of this issue here: #190 
@thomasyu888 Please answer the participant once this feature has been implemented.

**Comment by brucehoff** [comment] 2016-11-23 18:37
Ziming wrote the code but I have not deployed it yet.  I've marked the issue as 'Major' to keep at at the top of the list.

**Closed** 2017-01-26 23:54 UTC
Labels: discussion forum, Major
