### ISSUE TITLE
bm08: all containers spontaneously stopped

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#448] opened 2017-01-05 15:31 UTC
22 hours ago:
```
CREATED             STATUS                    PORTS               NAMES
04c637184cea        docker.synapse.org/syn7344325/tmii_2017_01_04_bs_20__ms_500@sha256:cde9a9082405dbca451f0eedcc817a64f89b8b951a5074b9c6c354c4969f48fb   "/train.sh"              23 hours ago        Exited (1) 22 hours ago                       7989141.bm08-1.TRAIN.TRAINING
a99e55f2fb9c        docker.synapse.org/syn7344325/tmii_2017_01_04_bs_30__ms_500@sha256:6ce8372c33f157a9f506e392ea323c377e50ba50b2a8063af076d979ccc412e9   "/train.sh"              23 hours ago        Exited (0) 23 hours ago                       archive.7989130.bm08-1.TRAIN.TRAINING
a89b3f5e9ed9        docker.synapse.org/syn7246508/train@sha256:1e65b787ce8309b703767a9340780c7f3097d146eddf58d3726cfaa27a17f2f2                           "/train.sh"              23 hours ago        Exited (0) 23 hours ago                       archive.7989122.bm08-1.TRAIN.TRAINING
ef50c7bddded        docker.synapse.org/syn7344325/tmii_2017_01_03_bs_60__ms_500@sha256:be66b8e483230a5f7524fea4c2eadccb517edec7b91ae35397e22bda2cc65bb7   "/train.sh"              23 hours ago        Exited (0) 23 hours ago                       archive.7989111.bm08-2.TRAIN.TRAINING
d3098fff964a        docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:f28e50d803fbb1b45f54373c25cea9f4712be8f0f6fc966f2911eadecb55328f                  "/train.sh"              24 hours ago        Exited (0) 24 hours ago                       archive.7988999.bm08-2.TRAIN.TRAINING
3a328d454cfe        docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:c5a150d0831cf4aa3c2a018c2930906e2e9bd6b9aed94823d60279a6da825b38                  "/train.sh"              24 hours ago        Exited (0) 24 hours ago                       archive.7988983.bm08-2.TRAIN.TRAINING
7ebf63202e4c        docker.synapse.org/syn7261049/dm-extract-features-11@sha256:b0f9641205c1eaea07673c574834accad86fa760895963b491b572d8c420f559          "/preprocess.sh"         34 hours ago        Exited (0) 33 hours ago                       archive.7987798.bm08-1.TRAIN.PREPROCESSING
40ffed597077        docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:d3296eb39f4939aafbdbe49022d3c22fdb74a94384d7bbff3391dbcb17d4e4c3                  "/train.sh"              34 hours ago        Exited (0) 34 hours ago                       archive.7988540.bm08-1.TRAIN.TRAINING
e3e065be84d8        docker.synapse.org/syn7246508/train@sha256:1e65b787ce8309b703767a9340780c7f3097d146eddf58d3726cfaa27a17f2f2                           "/train.sh"              34 hours ago        Exited (0) 34 hours ago                       archive.7987957.bm08-1.TRAIN.TRAINING
40ba0e16eb95        docker.synapse.org/syn7261049/dm-extract-features-11@sha256:b0f9641205c1eaea07673c574834accad86fa760895963b491b572d8c420f559          "/preprocess.sh"         34 hours ago        Exited (0) 34 hours ago                       archive.7987760.bm08-2.TRAIN.PREPROCESSING
f3f2f6c4f778        docker.synapse.org/syn7187934/medsieve@sha256:e9e7af33654050be1ce76be8b484f2a697931a7d5092e2bff66e27ec5e5ae511                        "/train.sh"              34 hours ago        Exited (0) 34 hours ago                       archive.7987289.bm08-1.TRAIN.TRAINING
408df5bf66f9        docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:70df7827e2a8df1a48c1f808f5e6a80bb82b2dbcf0936c8b89a60a39f43c1da7                  "/train.sh"              34 hours ago        Exited (0) 34 hours ago                       archive.7986378.bm08-2.TRAIN.TRAINING
7762ff239472        docker.synapse.org/syn7916535/dmc_shreyasnet_1_1@sha256:7d30d0c391bc3540ae8aa8cb0b2ca7835d53f04ea1fa1aad7e3a6d411f9fb4c2              "/train.sh"              35 hours ago        Exited (0) 34 hours ago                       archive.7916616.bm08-1.TRAIN.TRAINING
cb581e217f73        docker.synapse.org/syn7916535/dmc_shreyasnet_1_1@sha256:7d30d0c391bc3540ae8aa8cb0b2ca7835d53f04ea1fa1aad7e3a6d411f9fb4c2              "/train.sh"              35 hours ago        Exited (0) 34 hours ago                       archive.7916612.bm08-2.TRAIN.TRAINING
ff4f30ae2790        brucehoff/challengedockeragent                                                                                                        "/bin/sh -c 'exec mvn"   35 hours ago        Exited (1) 22 hours ago                       bm08-train-2
f97e041b16cc        brucehoff/challengedockeragent                                                                                                        "/bin/sh -c 'exec mvn"   35 hours ago        Exited (1) 22 hours ago                       bm08-train-1
```

**Comment by tschaffter** [comment] 2017-01-05 15:39
Let's keep this machine disconnected. I'll open a ticket for SoftLayer right now.

**Comment by tschaffter** [comment] 2017-01-05 15:49
DST ticket (for reference): https://ticketing.dst.ibm.com/problem/view/193478

**Comment by tschaffter** [comment] 2017-01-05 15:58
@brucehoff Can you highlight here the submission that were running at the time of the crash? Can you also keep a record - on Synapse or GitHub wiki - of all the submission that are running on a machine that encounter an issue? The goal is to help identifying common denominators (e.g. a team appear to be often involved when a crash occurs). Thanks!

**Comment by brucehoff** [comment] 2017-01-05 16:25
> @brucehoff Can you highlight here the submission that were running at the time of the crash? 

Yes, the submission was 7989141.

> Can you also keep a record - on Synapse or GitHub wiki - of all the submission that are running on a machine that encounter an issue?

I started a spreadsheet here:

https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=0

**Comment by tschaffter** [comment] 2017-01-05 18:49
@brucehoff The silver lining is that the issue occurred early in Round 2 and provide us with a minimal setup to reproduce the error. Can you think to a way to "replay" all the submissions that have run on bm08 until the machine became unresponsive? We need to make sure the containers to run will be available and if possible use the same challenge agent version that the one used.

**Comment by tschaffter** [comment] 2017-01-05 19:21
> I started a spreadsheet here:
Can you add
- the ID of the team that submitted
- the submission running on bm02 when the first agent was killed

**Comment by tschaffter** [comment] 2017-01-05 21:16
The issue seems to be that a fan of at least one GPU cards is not working, which led them to reach critically high temperatures. I've given the GPU to SoftLayer to stop the machine and proceed with the investigation.

**Comment by tschaffter** [comment] 2017-01-06 20:41
@brucehoff It's a finding from the DST. The fan has been replaced and the machine is back online. Can you reconnect bm08 and close this issue? Thanks!

**Closed** 2017-01-06 21:01 UTC
Labels: server instability
